package com.cihangirmercan;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.authentication.AnonymousAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller // This means that this class is a Controller 
public class MainController {
	@Autowired // This means to get the bean called userRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@Autowired
	private AuthorityRepository authorityRepository;

	@RequestMapping(value = "/", method = RequestMethod.GET)
	public String welcome(ModelMap model) {
		// This returns a JSON or XML with the users
		model.addAttribute("userList", userRepository.findAll());
		return "welcome";
	}

	// Login form
	@RequestMapping(value = "/login", method = RequestMethod.GET)
	public String login() {
		if (SecurityContextHolder.getContext().getAuthentication() != null
				&& SecurityContextHolder.getContext().getAuthentication().isAuthenticated()
				&& !(SecurityContextHolder.getContext().getAuthentication() instanceof AnonymousAuthenticationToken)) {
			// user has already logged in
			return "redirect:/";
		} else {
			return "login";
		}
	}

	// Login form
	@RequestMapping(value = "/register", method = RequestMethod.GET)
	public String register(ModelMap model) {
		if (SecurityContextHolder.getContext().getAuthentication() != null
				&& SecurityContextHolder.getContext().getAuthentication().isAuthenticated()
				&& !(SecurityContextHolder.getContext().getAuthentication() instanceof AnonymousAuthenticationToken)) {
			// user has already logged in
			return "redirect:/";
		} else {
			// to make available for binding, we need default user
			model.addAttribute("user", new User());
			return "register";
		}
	}

	@RequestMapping(value = "/register", method = RequestMethod.POST)
	public String register(@Valid User user, BindingResult result, HttpServletRequest request) {

		if (result.hasErrors()) {
			return "register";
		} else {
			User check = userRepository.findOne(user.getUsername());
			if (check == null) {
				userRepository.save(user);

				Authority auth = new Authority();
				auth.setUsername(user.getUsername());
				auth.setRole("ROLE_USER");
				authorityRepository.save(auth);
				return "redirect:/";
			} else { // it means that this username exists
				return "redirect:/register?error";
			}
		}	
	}
}